"""Integration tests for the complete UI-to-API flow.

Simulates the exact payload shapes sent by React views/modals:
- Onboarding.jsx -> POST /api/v1/onboarding
- CheckInModal.jsx -> POST /api/v1/checkins
- Train.jsx -> POST /api/v1/activities
- AmendmentModal.jsx -> PATCH /api/v1/activities/{id}
- Red-flag safety lockout enforcement
"""

import datetime as dt
import pytest
from fastapi.testclient import TestClient

from src.slickfit.api.app import app
from src.slickfit.db.session import engine
from src.slickfit.db.models import Base


@pytest.fixture(autouse=True)
def setup_test_db():
    Base.metadata.create_all(bind=engine)
    yield
    Base.metadata.drop_all(bind=engine)


@pytest.fixture
def client():
    return TestClient(app)


def test_complete_ui_to_api_end_to_end_flow(client: TestClient):
    # 1. Register a real athlete
    reg_res = client.post(
        "/api/v1/auth/register",
        json={"email": "athlete_ui@slickfit.test", "password": "SecurePassword123!", "full_name": "Rohan Patel"},
    )
    assert reg_res.status_code == 201, reg_res.text
    token = reg_res.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}

    # 2. Check Onboarding Status (Initial: Incomplete)
    status_res = client.get("/api/v1/onboarding/status", headers=headers)
    assert status_res.status_code == 200
    status_data = status_res.json()
    assert status_data["onboarding_completed"] is False
    assert status_data["active_event_id"] is None
    assert status_data["active_plan_id"] is None

    # 3. Submit Onboarding with EXACT payload format generated by Onboarding.jsx
    target_event_date = (dt.date.today() + dt.timedelta(days=45)).isoformat()
    ui_onboarding_payload = {
        "event": {
            "kind": "running",
            "sport": "running",
            "title": "Mumbai Half Marathon",
            "event_date": target_event_date,
            "goal_type": "finish",
            "target_value": 21.1,
            "target_unit": "km",
            "notes": "Target sub-2:00:00",
        },
        "baseline": {
            "experience_level": "beginner",
            "recent_weekly_km": 18.0,
            "recent_runs_per_week": 3,
            "recent_race_distance_km": 10.0,
            "recent_race_time_sec": 3300,  # 55:00 10K
            "easy_pace_sec_per_km": 390,
        },
        "availability": {
            "training_days": ["tuesday", "thursday", "saturday", "sunday"],
            "daily_time_cap_min": 60,
            "preferred_times": ["morning"],
            "environment_equipment": "road_outdoor",
        },
        "profile": {
            "age_band": "30-39",
            "region": "Mumbai",
        },
        "nutrition": {
            "dietary_pattern": "vegetarian",
            "regional_preference": "south_indian",
            "allergies": ["peanuts", "tree_nuts"],
        },
    }

    onboard_res = client.post("/api/v1/onboarding", json=ui_onboarding_payload, headers=headers)
    assert onboard_res.status_code == 201, onboard_res.text
    onboard_data = onboard_res.json()
    assert onboard_data["event"]["title"] == "Mumbai Half Marathon"
    assert len(onboard_data["plan"]["sessions"]) > 0
    plan_id = onboard_data["plan"]["id"]
    scheduled_sessions = onboard_data["plan"]["sessions"]
    first_session_id = scheduled_sessions[0]["id"]

    # 4. Check Onboarding Status (Now: Completed)
    status_res2 = client.get("/api/v1/onboarding/status", headers=headers)
    assert status_res2.status_code == 200
    assert status_res2.json()["onboarding_completed"] is True
    assert status_res2.json()["active_plan_id"] == plan_id

    # 5. Fetch Current Plan and Nutrition
    plan_res = client.get("/api/v1/plans/current", headers=headers)
    assert plan_res.status_code == 200
    assert plan_res.json()["id"] == plan_id

    nut_res = client.get("/api/v1/nutrition/today", headers=headers)
    assert nut_res.status_code == 200
    nut_data = nut_res.json()
    assert nut_data["carbs_g_min"] > 0
    assert nut_data["protein_g_min"] > 0
    assert nut_data["min_kcal"] > 0
    # Verify allergy filtering in meal ideas
    for meal in nut_data["meal_ideas"]:
        idea_text = meal["idea"].lower()
        assert "peanut" not in idea_text
        assert "badam" not in idea_text
        assert "kaju" not in idea_text

    # 6. Record Daily Check-in with EXACT payload format generated by CheckInModal.jsx
    today_str = dt.date.today().isoformat()
    ui_checkin_payload = {
        "local_date": today_str,
        "sleep_quality": 4,
        "energy_level": 4,
        "soreness_level": 2,
        "stress_level": 2,
        "pain_flag": False,
        "pain_area": "",
        "pain_severity": 0,
        "red_flag_symptom": False,
        "notes": "Feeling well rested and hydrated.",
    }

    checkin_res = client.post("/api/v1/checkins", json=ui_checkin_payload, headers=headers)
    assert checkin_res.status_code == 201, checkin_res.text
    assert checkin_res.json()["sleep_quality"] == 4

    # 7. Log Activity with EXACT payload format generated by Train.jsx
    ui_activity_payload = {
        "planned_session_id": first_session_id,
        "local_date": today_str,
        "activity_type": "running",
        "duration_min": 35.0,
        "distance_km": 5.2,
        "perceived_effort": 5,
        "completion_state": "completed",
        "early_stop_reason": "",
        "pain_flag": False,
        "pain_notes": "",
        "notes": "Smooth easy aerobic run.",
    }

    act_res = client.post("/api/v1/activities", json=ui_activity_payload, headers=headers)
    assert act_res.status_code == 201, act_res.text
    activity_id = act_res.json()["id"]
    assert act_res.json()["distance_km"] == 5.2

    # 8. Correct Activity with EXACT payload format generated by AmendmentModal.jsx
    ui_amendment_payload = {
        "distance_km": 5.4,
        "duration_min": 36.0,
        "perceived_effort": 6,
        "notes": "Corrected GPS watch distance drift.",
        "change_reason": "GPS recorded 5.2km; certified course watch measurement was 5.4km",
    }

    amend_res = client.patch(f"/api/v1/activities/{activity_id}", json=ui_amendment_payload, headers=headers)
    assert amend_res.status_code == 200, amend_res.text
    assert amend_res.json()["distance_km"] == 5.4
    assert amend_res.json()["perceived_effort"] == 6

    # Verify DataAmendment record was created
    amendments_res = client.get("/api/v1/data/amendments", headers=headers)
    assert amendments_res.status_code == 200
    amendments = amendments_res.json()
    assert len(amendments) >= 2  # distance and duration
    assert any(a["field_name"] == "distance_km" for a in amendments)

    # 9. Verify Red-Flag Medical Safety Lockout
    red_flag_checkin_payload = {
        "local_date": today_str,
        "sleep_quality": 2,
        "energy_level": 1,
        "soreness_level": 5,
        "stress_level": 4,
        "pain_flag": True,
        "pain_area": "Chest / Sternum",
        "pain_severity": 8,
        "red_flag_symptom": True,  # RED FLAG TRIGGER
        "notes": "Severe tightness in chest during morning walk.",
    }

    rf_res = client.post("/api/v1/checkins", json=red_flag_checkin_payload, headers=headers)
    assert rf_res.status_code == 201

    # Attempting to log a workout MUST be rejected with HTTP 403 Forbidden
    blocked_activity_payload = {
        "planned_session_id": None,
        "local_date": today_str,
        "activity_type": "running",
        "duration_min": 20.0,
        "distance_km": 3.0,
        "perceived_effort": 4,
        "completion_state": "completed",
        "early_stop_reason": "",
        "pain_flag": False,
        "pain_notes": "",
        "notes": "Attempting run after chest pain.",
    }

    blocked_res = client.post("/api/v1/activities", json=blocked_activity_payload, headers=headers)
    assert blocked_res.status_code == 403
    assert "SAFETY STOP" in blocked_res.json()["message"]

    # 10. Verify Unified History & Progress Trends
    hist_res = client.get("/api/v1/history", headers=headers)
    assert hist_res.status_code == 200
    feed = hist_res.json()
    item_types = {item["item_type"] for item in feed}
    assert "activity" in item_types
    assert "checkin" in item_types
    assert "adaptation" in item_types
    assert "amendment" in item_types

    prog_res = client.get("/api/v1/progress", headers=headers)
    assert prog_res.status_code == 200
    prog_data = prog_res.json()
    assert prog_data["total_runs_completed"] >= 1
    assert prog_data["total_distance_km"] > 0
